name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

    

jobs:
  build:
    run: |
      west build -s zmk/app -d "/tmp/tmp.RifTmeF5X7" -b "" -S "zmk-usb-logging" -- -DZMK_CONFIG=/tmp/zmk-config/config  -DZMK_EXTRA_MODULES='/__w/zmk-config-ble34/zmk-config-ble34' --Board=ble34   
#uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main